[WIP] Integrating action text for the post description
ajc113/bshomemade pull request #28
Opened 2023-06-15 04:13 UTC by gullariz12

Loom:
https://www.loom.com/share/1c2d9da5bfc0416c98ab52e711e75f7f

2023-06-15 04:40 UTC, tannakartikey requested changes

2023-06-15 04:40 UTC, tannakartikey commented on app/admin/posts.rb
> +      raw(resource.content_to_plain_text)
@gullariz12 let's render rich text (HTML) over here. Need to use `.trix-content`, right?

2023-06-15 04:40 UTC, tannakartikey commented on app/views/posts/index.html.erb
> +                                <p class="card-text"><%= post.content_to_plain_text&.truncate(500) %></p>
@gullariz12 let's render rich text (HTML) over here as well since we are not using the `posts/show` page.

2023-06-15 04:40 UTC, tannakartikey commented on app/views/posts/index.html.erb
> +                              <% end %>
@gullariz12 let's just use `post.image` here as before. Let's keep attachments to the description field.

2023-06-15 14:55 UTC, gullariz12 commented on app/admin/posts.rb
> +      raw(resource.content_to_plain_text)
I have done this for adapting the previous design to show images on the left side and text on the right side.
I will render the rich text body just as it is saved in the editor.

2023-06-15 14:55 UTC, gullariz12 commented on app/views/posts/index.html.erb
> +                                <p class="card-text"><%= post.content_to_plain_text&.truncate(500) %></p>
Sure.

2023-06-15 14:55 UTC, gullariz12 commented on app/views/posts/index.html.erb
> +                              <% end %>
So, we don't have to remove the existing image field from the DB right?
We will just remove it from the form so users will use the action text feature to attach images while creating the new posts and we don't have to migrate the existing posts data. That is the plan or I'm missing anything?

2023-06-17 10:35 UTC, tannakartikey approved these changes

2023-06-17 10:36 UTC, merged