[WIP] 39 contact form for hiring
ajc113/bshomemade pull request #41
Opened 2023-07-01 18:21 UTC by gullariz12

2023-07-03 05:01 UTC, tannakartikey approved these changes

2023-07-08 01:11 UTC, tannakartikey requested changes

2023-07-08 01:11 UTC, tannakartikey commented on config/initializers/action_mailer.rb
> +end
@gullariz12 the settings will be applied in the test environment too. I think it'd be best to put this under the production.rb file.

2023-07-08 01:11 UTC, tannakartikey commented on app/javascript/controllers/recaptcha_v2_controller.js
> +  }
@gullariz12 can we use `formEntries` and get all the fields at once?

For example:
```
Object.fromEntries(new FormData(this.contactFormTarget).entries())
```

2023-07-08 01:11 UTC, tannakartikey commented on app/javascript/controllers/recaptcha_v2_controller.js
> +  initialize() {
What if we use the `connect()` method of Stimulus here?

2023-07-08 01:11 UTC, tannakartikey commented on app/javascript/controllers/recaptcha_v2_controller.js
> +    $('#job-applicant-form').addClass('d-none');
Can declare job-application-form as Stimulus target?

2023-07-08 01:27 UTC, tannakartikey requested changes

2023-07-08 01:27 UTC, tannakartikey commented on app/views/job_applicant_mailer/notify_applicant.html.erb
> +</div>
```suggestion
      <span>We will review your information carefully and contact you when we have opportunities available.</span><br /><br />
      <span>Sincerely,</span><br />
      <span>Brooke Costa</span><br />
      <span>B's Ice Cream</span><br />
    </p>
  </div>
</div>
```

2023-07-08 01:28 UTC, tannakartikey requested changes

2023-07-08 01:28 UTC, tannakartikey commented on app/mailers/job_applicant_mailer.rb
> +    mail(to: 'brookeshomemade@gmail.com', subject: 'New employment request')
```suggestion
    mail(to: 'brookeshomemade@gmail.com', subject: 'New Job Application Received')
```

2023-07-08 01:32 UTC, tannakartikey requested changes

2023-07-08 01:32 UTC, tannakartikey commented on app/views/job_applicant_mailer/notify_admin.html.erb
> +  </div>
```suggestion
  <div style="margin-top: 25px;">
    <p>New Job application with below high level information has been received.</p><br>
    <p>Applicant Name: <%= params[:applicant_name] %></p>
    <p>Applicant Email: <%= params[:applicant_email] %></p>
    <p>Applicant Selected Position: <%= params[:selected_position] %></p>
    <%= link_to "View full application", admin_job_applicant_url(JobApplicant.find_by!(email: params[:applicant_email])) %>
  </div>
```

2023-07-08 10:45 UTC, gullariz12 commented on app/javascript/controllers/recaptcha_v2_controller.js
> +  }
I've given try to it but it will nest params `job_applicant['email]` just like popular in JS world.
And in Rails world we and expecting params should be nest like this job_applicant: { email: '', name: '', ....} to permit them.
Can we go with this way so we can keep our Rails conventions in place otherwise we have to update our Rails controller as well and add some logic in the form so it will send params like this `job_applicant['email]`.

2023-07-08 10:46 UTC, gullariz12 commented on app/javascript/controllers/recaptcha_v2_controller.js
> +  initialize() {
Nothing will go wrong. I will update it.
Since `initialize ()` is called before the `connect()` I just want to show recaptcha as soon as the controller connect to DOM.

2023-07-08 10:46 UTC, gullariz12 commented on app/javascript/controllers/recaptcha_v2_controller.js
> +    $('#job-applicant-form').addClass('d-none');
We can't set the form as a target for the controller because our form will get in DOM first and controller will be initialized only if the recaptcha V3 wil be failed to verify.

2023-07-08 12:15 UTC, tannakartikey approved these changes

2023-07-08 16:03 UTC, merged